language: python
sudo: required
dist: trusty
python:
  - "3.4"

addons:
  apt:
    sources:
     - sourceline: 'deb [trusted=yes] https://debian.unknown-horizons.org/travis/ /'

before_install:
  - "sudo apt-get update"

install:
  - "sudo apt-get install python3-fife" # libfifechan0.1.4 not avalibale yet
  - "pip3 install -r requirements.txt"

script:
  - "cp -a /usr/lib/python3/dist-packages/fife/ $VIRTUAL_ENV/lib/python3.4/site-packages/"
  - "prename 's/\\.cpython-34m-x86_64-linux-gnu/.cpython-34m/' $VIRTUAL_ENV/lib/python3.4/site-packages/fife/*.so"
  - python3 -c 'from fife import fife; print(fife.getVersion())'
  - isort -c -rc horizons tests *.py
  - pycodestyle horizons tests *.py development
  - COVERAGE_FILE=.coverage.nongui pytest --verbose --cov --cov-report= -rs

after_success:
  - coverage combine
  - coveralls

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#unknown-horizons"
      - "chat.freenode.net#unknown-horizons-de"
    skip_join: false
    use_notice: false
