language: python
sudo: required
dist: trusty
python:
  - "3.4"
# command to install dependencies
addons:
  apt:
    sources:
      - sourceline: 'deb [trusted=yes] http://joker.someserver.de/uh/trusty /'
before_install:
  - "sudo apt-get update"
  - "export DISPLAY=:99.0"
  - "export PYTHON_VERSION=python3.4"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  #- "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - "sudo apt-get install y build-essential libalsa-ocaml-dev libsdl2-dev libboost-dev libsdl2-ttf-dev libsdl2-image-dev libvorbis-dev libalut-dev python3.4 python3-dev libboost-regex-dev libboost-filesystem-dev libboost-test-dev swig zlib1g-dev libopenal-dev git python3-yaml python3-future libxcursor1 libxcursor-dev cmake cmake-data libtinyxml-dev libpng-dev libglew-dev"
  - "git clone https://github.com/fifengine/fifechan.git && cd fifechan"
  - "mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .."
  - "make && sudo make install"
  - "cp -a /usr/lib/$PYTHON_VERSION/dist-packages/fife/ $VIRTUAL_ENV/lib/$PYTHON_VERSION/site-packages/"
  - "prename 's/\\.x86_64-linux-gnu//' $VIRTUAL_ENV/lib/$PYTHON_VERSION/site-packages/fife/*.so"
  - "pip install -r requirements.txt"
  - "pip install coverage coveralls"
script: 
  - python -c 'from fife import fife; print fife.getVersion()'
  - isort -c -rc horizons tests run_*.py
  - pycodestyle --count horizons/ tests/ development/
  - COVERAGE_FILE=.coverage.nongui python run_tests.py --verbose --nologcapture --with-coverage
  - RUNCOV=1 python run_tests.py -a gui tests/gui --verbose --nologcapture
after_success:
  - coverage combine
  - coveralls
notifications:
  irc: "irc.freenode.org#unknown-horizons"
  email: false
